[package]
name = "ferris_dodger"
version = "0.1.0"
authors = ["JP Moresmau Jjp@moresmau.fr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.2.1", features = [ "wav" ] }
rand = "0.7.3"